# Generated by Django 3.0.3 on 2020-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
